version: '3.9'

services:
  # ============================================================================
  # NGINX REVERSE PROXY
  # ============================================================================
  nginx:
    image: nginx:1.25-alpine
    container_name: gtm_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
      - ./web_local:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
      - api3
    networks:
      - gtm_network

  # ============================================================================
  # API SERVERS (Rating API) x3 for load balancing
  # ============================================================================
  api1:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: gtm_api1
    restart: unless-stopped
    env_file:
      - ./.env
    expose:
      - "5000"
    networks:
      - gtm_network

  api2:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: gtm_api2
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - api1
    expose:
      - "5000"
    networks:
      - gtm_network

  api3:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: gtm_api3
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - api1
    expose:
      - "5000"
    networks:
      - gtm_network

  # ============================================================================
  # TELEGRAM BOT
  # ============================================================================
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: gtm_bot
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./logs:/app/logs
    networks:
      - gtm_network

  # ============================================================================
  # REDIS (Queue backend for referrals/worker)
  # ============================================================================
  redis:
    image: redis:7-alpine
    container_name: gtm_redis
    restart: unless-stopped
    expose:
      - "6379"
    networks:
      - gtm_network

  # ============================================================================
  # REFERRALS MICROSERVICE (FastAPI) + WORKER (RQ)
  # ============================================================================
  referrals_api:
    build:
      context: ./referrals
      dockerfile: Dockerfile
    container_name: gtm_referrals_api
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - RQ_QUEUE_NAME=gtm
    expose:
      - "8000"
    depends_on:
      - redis
    networks:
      - gtm_network

  referrals_worker:
    build:
      context: ./referrals
      dockerfile: Dockerfile
    container_name: gtm_referrals_worker
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - RQ_QUEUE_NAME=gtm
    command: ["python", "worker_entry.py"]
    depends_on:
      - redis
    networks:
      - gtm_network

# ============================================================================
# NETWORKS
# ============================================================================
networks:
  gtm_network:
    driver: bridge 