version: '3.8'

services:
  # ============================================================================
  # NGINX REVERSE PROXY
  # ============================================================================
  nginx:
    image: nginx:alpine
    container_name: gtm_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
      - ./web:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - gtm_network

  # ============================================================================
  # API SERVER (Rating API)
  # ============================================================================
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: gtm_api
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./logs:/app/logs
    networks:
      - gtm_network

  # ============================================================================
  # TELEGRAM BOT
  # ============================================================================
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: gtm_bot
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./logs:/app/logs
    networks:
      - gtm_network

# ============================================================================
# NETWORKS
# ============================================================================
networks:
  gtm_network:
    driver: bridge 