[build]
  command = """
    # Install Flutter SDK
    git clone https://github.com/flutter/flutter.git -b stable --depth 1 flutter
    export PATH="$PWD/flutter/bin:$PATH"
    
    # Configure Flutter for web
    flutter config --enable-web
    flutter doctor
    
    # Build the app with environment variables
    flutter build web --release --dart-define=SUPABASE_URL=$SUPABASE_URL --dart-define=SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY --dart-define=WEBAPP_VERSION=$WEBAPP_VERSION --dart-define=RATING_API_BASE_URL=$RATING_API_BASE_URL --dart-define=SUPABASE_AI_BUCKET=$SUPABASE_AI_BUCKET --dart-define=SUPABASE_AI_FOLDER=$SUPABASE_AI_FOLDER --dart-define=TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
    
    # Copy build files to publish directory
    cp -r build/web/. ./
    cp web/_redirects _redirects
  """
  publish = "."

[build.environment]
  FLUTTER_WEB = "true"
  NODE_VERSION = "18"

# Важно! Редиректы для SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Дополнительные заголовки безопасности
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Кэширование статических ресурсов
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"