[build]
builder = "DOCKERFILE"
buildCommand = "flutter build web --release"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
PORT = "8080"
FLUTTER_WEB = "true"
FLUTTER_WEB_AUTO_DETECT = "true"